services:
  api:
    build: ./Dockerfile
    container_name: pokeapi
    command: fastapi run main.py --port 8080
    ports:
      80:8080
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: secure_password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq
volumes:
  rabbitmq_data:
  rabbitmq_log: