services:
  api:
    build: ./
    container_name: pokeapi
    command: uv run fastapi dev main.py --port 8080 --host 0.0.0.0
    ports:
      - 8080:8080
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: secure_password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq
volumes:
  rabbitmq_data:
  rabbitmq_log:
